/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#0b1326',
          dim: '#0b1326',
          bright: '#31394d',
          'container-lowest': '#060e20',
          'container-low': '#131b2e',
          container: '#171f33',
          'container-high': '#222a3d',
          'container-highest': '#2d3449',
          variant: '#2d3449',
          tint: '#adc6ff',
        },
        'on-surface': {
          DEFAULT: '#dae2fd',
          variant: '#c1c6d7',
        },
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: {
          DEFAULT: '#8b90a0',
          variant: '#414755',
        },
        primary: {
          DEFAULT: '#adc6ff',
          on: '#002e69',
          container: '#4b8eff',
          'on-container': '#00285c',
          inverse: '#005bc1',
          fixed: '#d8e2ff',
          'fixed-dim': '#adc6ff',
          'on-fixed': '#001a41',
          'on-fixed-variant': '#004493',
        },
        secondary: {
          DEFAULT: '#49ddb8',
          on: '#00382b',
          container: '#05bb98',
          'on-container': '#004436',
          fixed: '#6bfad3',
          'fixed-dim': '#49ddb8',
          'on-fixed': '#002018',
          'on-fixed-variant': '#005140',
        },
        tertiary: {
          DEFAULT: '#ffb4aa',
          on: '#690003',
          container: '#ff5545',
          'on-container': '#5c0002',
          fixed: '#ffdad5',
          'fixed-dim': '#ffb4aa',
          'on-fixed': '#410001',
          'on-fixed-variant': '#930005',
        },
        error: {
          DEFAULT: '#ffb4ab',
          on: '#690005',
          container: '#93000a',
          'on-container': '#ffdad6',
        },
        background: '#0b1326',
        'on-background': '#dae2fd',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
      },
    },
  },
  plugins: [],
}
